name: Terraform Workflow

on:
  push:
    paths:
      - '**.java'
  workflow_dispatch:

jobs:
  build_Docker_image:
    name: Push Docker image to Docker hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
      - name: Checkstyle check
        run: mvn -ntp checkstyle:check -Dcheckstyle.violationSeverity=warning
      - name: Clean
        run: mvn -ntp clean
      - name: Build
        run: mvn -ntp compile
      - name: Tests
        run: mvn -ntp test -Dtest='MainPresenterTest'
